pip3 install xlutils 
pip3 install xlwt 
pip3 install xlrd 
pip3 install chardet
pip3 install xlsxwriter 
pip3 install demjson 
pip3 install xmltodict 
pip3 install configparser 
pip3 install shutil 
pip3 install PyQt5 
pip3 install cx_Oracle 
pip3 install pymysql 
pip3 install pymssql 
pip3 install apscheduler
pip3 install yagmail 
pip3 install openpyxl 
pip3 install jsonschema 
pip3 install requests 
